const questions = {
  fr: {
    niveau1: [
      { question: "Comment dire 'salut' en algérien ?", answers: ["Choukran", "Salam", "Kho", "Mlih"], correct: 1 },
      { question: "Que signifie 'saha' ?", answers: ["Bonjour", "Oui", "Merci", "Au revoir"], correct: 2 },
      { question: "Comment dire 'non' en algérien ?", answers: ["Lala", "Lish", "Lil", "Lyom"], correct: 0 },
      { question: "Comment dire 'oui' en algérien ?", answers: ["Ih", "Wa", "Iya", "Ana"], correct: 0 },
      { question: "Que signifie 'bezzaf' en algérien ?", answers: ["Beaucoup", "Peu", "Rien", "Tout"], correct: 0 },
      { question: "Que signifie 'ana' en algérien ?", answers: ["Moi", "Toi masculin", "Toi féminin", "Lui"], correct: 0 },
      { question: "Que signifie 'nti' en algérien ?", answers: ["Moi", "Toi masculin", "Toi féminin", "Lui", "Elle"], correct: 2 },
      { question: "Que signifie '3lesh' ?", answers: ["Où", "Quand", "Comment", "Pourquoi"], correct: 3 },
      { question: "Que signifie 'kifesh' ?", answers: ["Qui", "Comment", "Où", "Quand"], correct: 1 },
      { question: "Que signifie 'win' ?", answers: ["Où", "Pourquoi", "Comment", "Quand"], correct: 0 },
    ],
    niveau2: [
      { question: "Que signifie 'khoya' en algérien ?", answers: ["Mon ami", "Mon cousin", "Mon frère", "Mon cher"], correct: 2 },
      { question: "Que signifie 'chouf' en algérien ?", answers: ["Écoute", "Sors", "Viens", "Regarde"], correct: 3 },
      { question: "Comment dire 'qui' en algérien ?", answers: ["Weqtach", "Chkoun", "Win", "Chehal"], correct: 1 },
      { question: "Comment dire 'merci' en algérien ?", answers: ["Saha", "Techekur", "Iselmek bsahtek"], correct: 0 },
      { question: "Comment dire 'toi' en masculin en algérien ?", answers: ["Ana", "Nta", "Nti", "Hna"], correct: 1 },
      { question: "Comment dire 'voiture' en algérien ?", answers: ["Tonobil", "Araba", "Machina", "Teyara"], correct: 0 },
    ],
    niveau3: [
      { question: "Comment répondre à 'bsahtek' ?", answers: ["Ichoufek", "Sebtek", "Iselmek", "Darek"], correct: 2 },
      { question: "Que signifie 'chbab' en algérien ?", answers: ["Beau", "Grand", "Riche", "Intelligent"], correct: 0 },
      { question: "Que signifie 'ropa' en algérien ?", answers: ["Chaussures", "Vêtements", "Pantalon", "Robe"], correct: 3 },
      { question: "Comment dire 'table' en algérien ?", answers: ["Bab", "Frach", "Tabla", "Koursi"], correct: 2 },
      { question: "Comment dire 'maison' en algérien ?", answers: ["Jnan", "Dar", "Bit", "Houch"], correct: 1 },
      { question: "Comment dire 'aujourd'hui' en algérien ?", answers: ["Ghedwa", "Lbareh", "Smana", "Lyom"], correct: 3 },
      { question: "Comment dire 'maintenant' en algérien ?", answers: ["Weqt", "Doka", "Dqiqa", "Sa3a"], correct: 1 },
    ],
  },
  en: {
    niveau1: [
      { question: "How do you say hello in Algerian?", answers: ["Choukran", "Salam", "Kho", "Mlih"], correct: 1 },
      { question: "What does 'saha' mean?", answers: ["Hello", "Yes", "Thanks", "Goodbye"], correct: 2 },
      { question: "How do you say no in Algerian?", answers: ["Lala", "Lish", "Lil", "Lyom"], correct: 0 },
      { question: "How do you say yes in Algerian?", answers: ["Ih", "Wa", "Iya", "Ana"], correct: 0 },
      { question: "What does 'ana' mean in Algerian?", answers: ["Me", "You masculine", "You feminine", "Him"], correct: 0 },
      { question: "What does 'nti' mean in Algerian?", answers: ["Me", "You masculine", "You feminine", "Him", "Her"], correct: 2 },
      { question: "What does '3lesh' mean?", answers: ["Where", "When", "How", "Why"], correct: 3 },
      { question: "What does 'kifesh' mean?", answers: ["Who", "How", "Where", "When"], correct: 1 },
      { question: "What does 'win' mean?", answers: ["Where", "Why", "How", "When"], correct: 0 },
    ],
    niveau2: [
      { question: "What does 'khoya' mean in Algerian?", answers: ["My friend", "My cousin", "My brother", "My dear"], correct: 2 },
      { question: "What does 'chouf' mean in Algerian?", answers: ["Listen", "Go out", "Come", "Look"], correct: 3 },
      { question: "How do you say 'who' in Algerian?", answers: ["Weqtach", "Chkoun", "Win", "Chehal"], correct: 1 },
      { question: "How do you say 'thank you' in Algerian?", answers: ["Saha", "Techekur", "Iselmek" ,"bsahtek"], correct: 0 },
      { question: "How do you say 'you' (masculine) in Algerian?", answers: ["Ana", "Nta", "Nti", "Hna"], correct: 1 },
      { question: "How do you say 'car' in Algerian?", answers: ["Tonobil", "Araba", "Machina", "Teyara"], correct: 0 },
    ],
    niveau3: [
      { question: "How do you respond to 'bsahtek'?", answers: ["Ichoufek", "Sebtek", "Iselmek", "Darek"], correct: 2 },
      { question: "What does 'chbab' mean in Algerian?", answers: ["Beautiful", "Tall", "Rich", "Intelligent"], correct: 0 },
      { question: "What does 'ropa' mean in Algerian?", answers: ["Shoes", "Clothes", "Pants", "Dress"], correct: 3 },
      { question: "How do you say 'table' in Algerian?", answers: ["Bab", "Frach", "Tabla", "Koursi"], correct: 2 },
      { question: "How do you say 'house' in Algerian?", answers: ["Jnan", "Dar", "Bit", "Houch"], correct: 1 },
      { question: "How do you say 'today' in Algerian?", answers: ["Ghedwa", "Lbareh", "Smana", "Lyom"], correct: 3 },
      { question: "How do you say 'now' in Algerian?", answers: ["Weqt", "Doka", "Dqiqa", "Sa3a"], correct: 1 },
    ],
  },
};

export default questions;
